### ISSUE TITLE
"Use this template" not available.

### ISSUE THREAD

**Issue by kerednai** [DataStax-Examples/glitch-astra-starter#1]
The first step in the "Github" section reads: Click Use this template at the top of the GitHub Repository.
However there is no "Use this template" button as I assume this repo has not been setup as a template repository?

![image](https://user-images.githubusercontent.com/8450657/133323798-bc7f026a-aa58-4b52-86af-a353cf27ab25.png)

**Comment by kidrecursive** [comment]
Ah, that's correct! I've updated the repository.
